### ISSUE TITLE
Update dep shell-escape

### ISSUE THREAD

**Issue by seangenabe** [arjunmehta/node-unparse-args#1]
The version of shell-escape that you're using prepends `$` to escaped output, e.g. `[ foo.bar ]` will yield `$'foo.bar'`. Breaks things on Windows.

**Comment by arjunmehta** [comment]
@seangenabe ah, do you know if a new version fixes this?

**Comment by seangenabe** [comment]
Yes, I actually played with it in the console and debugged the code to notice it. It doesn't fix all of my issues with it though, but I've posted there instead. But updating would be nice.

**Comment by arjunmehta** [comment]
Okay cool, just tested (had to update what to expect from tests.).
Version bump to 1.2.0 as this can be considered a feature change (support for windows). Should be backwards compatible on *nix systems.

Thanks for the heads up on the issue!
