### ISSUE TITLE
false boolean values are not being handled correctly

### ISSUE THREAD

**Issue by satazor** [arjunmehta/node-unparse-args#2]
`--no--coverage` -> yargs -> `{ coverage: false }` -> unparse -> `--coverage`

It should generate `--no-coverage` or `--coverage false`

**Comment by satazor** [comment]
Are you willing to accept a PR to address this bug?

**Comment by arjunmehta** [comment]
@satazor Yes of course! Please.

**Comment by arjunmehta** [comment]
Fixed in v1.2.0

**Comment by satazor** [comment]
I ended up doing my own module for yargs which is named [yars-unparse](https://github.com/moxystudio/yargs-unparse
